[build]
  command = "npm run build"
  publish = "out"
  
# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Set cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set cache headers for images
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.2.3"
